"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const route = fs.readFileSync(path.join(root, "src/routes/gold-purchase.routes.js"), "utf8");
const service = fs.readFileSync(path.join(root, "src/services/financial-settlement.service.js"), "utf8");
const baseline = fs.readFileSync(path.join(root, "src/bootstrap/permission-baseline-v1.js"), "utf8");
const workspace = fs.readFileSync(path.join(root, "..", "features/gold-purchases/components/GoldPurchaseDraftWorkspace.tsx"), "utf8");
assert.match(route, /\/cgp\/drafts\/:id\/settlements/);
assert.match(route, /gold_purchase\.cgp\.settle/);
assert.match(route, /businessStatus\)\.toUpperCase\(\) !== "POSTED"/);
assert.match(route, /executeCustomerPayoutSettlement/);
assert.match(route, /sourceDocumentId: document\.id/);
assert.match(route, /CGP_SETTLEMENT_LIABILITY_SOURCE_INVALID/);
assert.doesNotMatch(route, /customers\/:id\/gold\/deposit/);
assert.doesNotMatch(route, /gold_purchase\.cgp\.post.*settlements/);
assert.match(service, /CUSTOMER_FINANCIAL_LIABILITY_OVERSETTLEMENT/);
assert.match(service, /FINANCIAL_SETTLEMENT_BANK_REFERENCE_REQUIRED/);
assert.match(service, /Idempotency key was already used/);
assert.match(baseline, /gold_purchase\.cgp\.settle/);
assert.match(workspace, /gold_purchase\.cgp\.settle/);
assert.match(workspace, /data-cgp-settlement-form/);
assert.match(workspace, /selected\.businessStatus === "POSTED" && canSettle/);
assert.match(workspace, /bankReference/);
console.log("CGP_SETTLEMENT_STATIC_VERIFIER: PASS");
