"use strict";

/**
 * Deterministic seed configuration constants for client-demo-transactions-v1.
 */
module.exports = {
  SEED_VERSION: "client-demo-transactions-v1",
  ADMIN_EMAIL: "admin@admin.com",
  ADMIN_PASSWORD: "123456",
  DEFAULT_COMPANY_ID: "CMP-DEMO",
  DEFAULT_BRANCH_ID: "BR-DXB",

  // Stable demo date range
  START_DATE: "2026-01-01",
  MID_DATE_1: "2026-01-15",
  MID_DATE_2: "2026-02-15",
  END_DATE: "2026-03-31",

  // Vouchers
  VOUCHER_CODE: "GV-DEMO-001",

  // Deterministic References & Keys mapping
  REFERENCES: {
    PO_1: "DEMO-PO-001",
    PO_2: "DEMO-PO-002",
    PO_3: "DEMO-PO-003",
    SALE_CASH_1: "DEMO-SALE-CASH-001",
    SALE_CASH_2: "DEMO-SALE-CASH-002",
    SALE_INSTALLMENT: "DEMO-SALE-INSTALLMENT-001",
    SALE_DEPOSIT: "DEMO-SALE-DEPOSIT-001",
    RETURN: "DEMO-RETURN-001",
    EXCHANGE: "DEMO-EXCHANGE-001",
    INSTALLMENT_PAY_1: "DEMO-INSTALLMENT-PAY-001",
    INSTALLMENT_PAY_2: "DEMO-INSTALLMENT-PAY-002",
    GOLD_DEPOSIT: "DEMO-GOLD-DEPOSIT-001",
    GOLD_USE: "DEMO-GOLD-USE-001",
    GOLD_PAYOUT: "DEMO-GOLD-PAYOUT-001",
    SUPPLIER_PAY: "DEMO-SUPPLIER-PAY-001",
    JOURNAL: "DEMO-JOURNAL-001",
    VOUCHER_ISSUE: "DEMO-VOUCHER-001",
    TREASURY_IN: "DEMO-TREASURY-IN-001",
    TREASURY_OUT: "DEMO-TREASURY-OUT-001",
    CREDIT_DEPOSIT: "DEMO-CREDIT-DEPOSIT-001",
    CREDIT_REFUND: "DEMO-CREDIT-REFUND-001",
    DRAFT_INVOICE: "DEMO-DRAFT-INVOICE-001"
  }
};
