"use strict";

const path = require("path");
const models = require(path.resolve(__dirname, "..", "..", "..", "src", "models"));
const config = require("./config");

// In-memory cache for resolved database references
const ctx = {
  company: null,
  branches: {},
  customers: {},
  suppliers: {},
  accounts: {},
  products: {},
  assets: {},
  results: {} // Dynamic results (e.g. invoice IDs generated by seed checkout)
};

/**
 * Loads required database reference objects deterministically.
 */
async function loadContext() {
  // 1. Load Company
  ctx.company = await models.Company.findByPk(config.DEFAULT_COMPANY_ID);
  if (!ctx.company) {
    throw new Error(`Company '${config.DEFAULT_COMPANY_ID}' not found in database. Run baseline seeds first.`);
  }

  // 2. Load Branches
  const branchesList = await models.Branch.findAll({ where: { companyId: config.DEFAULT_COMPANY_ID } });
  for (const b of branchesList) {
    ctx.branches[b.id] = b.toJSON();
  }

  if (!ctx.branches[config.DEFAULT_BRANCH_ID]) {
    throw new Error(`Default branch '${config.DEFAULT_BRANCH_ID}' not found in database.`);
  }

  // 3. Load Customers by email
  const customersList = await models.Customer.findAll({ where: { companyId: config.DEFAULT_COMPANY_ID } });
  for (const c of customersList) {
    // Map by email for deterministic lookup
    if (c.email) {
      ctx.customers[c.email.trim().toLowerCase()] = c.toJSON();
    }
  }

  // Verify we have enough customers for different cycles:
  // mariam@example.com (installment/VIP), khaled@example.com (balance/credit), dana@example.com (cash/gold)
  const requiredCustomerEmails = ["mariam@example.com", "khaled@example.com", "dana@example.com"];
  for (const email of requiredCustomerEmails) {
    if (!ctx.customers[email]) {
      throw new Error(`Required customer '${email}' not found in database. Run baseline seeds first.`);
    }
  }

  // 4. Load Suppliers by name
  const suppliersList = await models.Supplier.findAll({ where: { companyId: config.DEFAULT_COMPANY_ID } });
  for (const s of suppliersList) {
    ctx.suppliers[s.name.trim().toLowerCase()] = s.toJSON();
  }

  const requiredSuppliers = ["emirates diamonds", "gulf pearls", "swiss time me", "colombia gems"];
  for (const sName of requiredSuppliers) {
    if (!ctx.suppliers[sName]) {
      throw new Error(`Required supplier '${sName}' not found in database. Run baseline seeds first.`);
    }
  }

  // 5. Load Accounts by code
  const accountsList = await models.Account.findAll({ where: { companyId: config.DEFAULT_COMPANY_ID } });
  for (const a of accountsList) {
    ctx.accounts[a.code] = a.toJSON();
  }

  // 6. Load seeded client-demo Assets
  const assetsList = await models.Asset.findAll({ where: { companyId: config.DEFAULT_COMPANY_ID } });
  for (const a of assetsList) {
    ctx.assets[a.id] = a.toJSON();
  }

  // Verify that the inventory seeder has run and created client-demo variants
  const requiredAssetIds = [
    "AST-CD-gw-jewellery-1",
    "AST-CD-gw-jewellery-2",
    "AST-CD-gw-bar",
    "AST-CD-gp",
    "AST-CD-dd-jewellery",
    "AST-CD-dd-loose",
    "AST-CD-gs-jewellery",
    "AST-CD-gs-loose",
    "AST-CD-pl-jewellery",
    "AST-CD-pl-loose",
    "AST-CD-watch"
  ];
  for (const aid of requiredAssetIds) {
    if (!ctx.assets[aid]) {
      throw new Error(`Required client-demo asset '${aid}' not found in database. Run inventory seeder first.`);
    }
  }

  // 7. Load Products (automatically created from Assets by bootstrap migration or opening balance)
  const productsList = await models.Product.findAll({ where: { companyId: config.DEFAULT_COMPANY_ID } });
  for (const p of productsList) {
    ctx.products[p.productCode] = p.toJSON();
  }

  return ctx;
}

module.exports = {
  ctx,
  loadContext
};
